<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Shift Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_success'] = array(
        'title' => 'Encrypted Cipher',
        'page callback' => 'cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $direction = array( 0 => 'left', 1 => 'right');

    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter the shift value'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    // $form['shift_direction'] = array(
    //     '#title' => 'Shift Direction',
    //     '#type' => 'radios',
    //     '#options' => $direction,
    //     '#description' => t('Select shift direction'),
    //     '#required' => TRUE,
    // );
    $form['shift_phrase'] = array(
        '#title' => 'Phrase to encode',
        '#type' => 'textfield',
        '#description' => t('Type phrase to encode'),
        // '#element_validate' => array();
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encode',
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    // $shift_direction = $form_state['values']['shift_direction'];
    $shift_phrase = str_split(strtolower($form_state['values']['shift_phrase']));

    $alphabet = range('a', 'z');
    $flip = array_flip($alphabet);

    $n = count($shift_phrase);
    // var_dump($shift_phrase);

    $output = "";

    for ($i = 0; $i < $n; $i++) {
        $output .= $alphabet[($flip[$shift_phrase[$i]] + $shift_value) % 26];
    }

    $_SESSION['output'] = "Encrypted Phrase: " . $output;
    $form_state['redirect'] = 'cipher_success';
}

function cipher_success() {
    return $_SESSION['output'];
}
